version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image:  cimg/node:16.13-browsers
    resource_class: large
    environment:
      LOGS_DIR: /tmp/ngx-mime-build/logs
      BROWSER_PROVIDER_READY_FILE: /tmp/ngx-mime-build/readyfile
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: echo 127.0.0.1 lh | sudo tee -a /etc/hosts
      - run: find ./apps/integration* -type f -exec sed -i 's/localhost/lh/' {} \;
      - run: 'mkdir -p $LOGS_DIR'
      - run: 'chmod +x ./scripts/ci/build-and-test.sh'
      - run: 'chmod +x ./scripts/lambdatest/start-tunnel.sh'
      - run: 'chmod +x ./scripts/lambdatest/wait-tunnel.sh'
      - run: 'chmod +x ./scripts/lambdatest/stop-tunnel.sh'
      - run: 'chmod +x ./apps/integration-e2e/scripts/wait-on.sh'
      - run:
          name: Build and test
          command: './scripts/ci/build-and-test.sh'
