version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
  nx: nrwl/nx@1.6.2
jobs:
  build:
    docker:
      - image: cimg/node:20.4.0-browsers
    resource_class: large
    environment:
      LOGS_DIR: /tmp/ngx-mime-build/logs
      BROWSER_PROVIDER_READY_FILE: /tmp/ngx-mime-build/readyfile
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas
      - run: 'mkdir -p $LOGS_DIR'
      - run: 'chmod +x ./scripts/ci/build-and-test.sh'
      - run: 'chmod +x ./scripts/lambdatest/start-tunnel.sh'
      - run: 'chmod +x ./scripts/lambdatest/wait-tunnel.sh'
      - run: 'chmod +x ./scripts/lambdatest/stop-tunnel.sh'
      - run: 'chmod +x ./scripts/ci/wait-on.sh'
      - run: 'yarn install'
      - run:
          name: Build and test
          command: './scripts/ci/build-and-test.sh'
