version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
    environment:
      LOGS_DIR: /tmp/ngx-mime-build/logs
      SAUCE_USERNAME: ronnymikalsen
      SAUCE_ACCESS_KEY: fa5b212d-466a-4e29-b593-957164bfc10b
      BROWSER_PROVIDER_READY_FILE: /tmp/ngx-mime-build/readyfile
    steps:
      - checkout
      - run: 'mkdir -p $LOGS_DIR'
      - run: 'chmod +x ./scripts/ci/build-and-test.sh'
      - run: 'chmod +x ./scripts/saucelabs/start-tunnel.sh'
      - run: 'chmod +x ./scripts/saucelabs/wait-tunnel.sh'
      - run: 'chmod +x ./scripts/saucelabs/stop-tunnel.sh'
      - run: 'chmod +x ./apps/integration-e2e/scripts/wait-on.sh'
      - run: 'yarn install'
      - run:
          name: Build and test
          command: './scripts/ci/build-and-test.sh'
